###################################################################################################################################################################################################################
##                                                                                                      生产环境                                                                                                 ##
###################################################################################################################################################################################################################
server:
    port: 9000
    context-path:

logging:
    level:
        com.jidao: INFO
        org.springframework.web: ERROR
        org.springframework.jdbc.core.JdbcTemplate: ERROR
        org.springframework.jdbc.core.StatementCreatorUtils: ERROR

spring:
    datasource:
        name: test
        url: jdbc:mysql://10.51.117.231:3306/jidao_riot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: jidaosql##!@

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    freemarker:
        cache: false
        request-context-attribute: request

myProps: #自定义的属性和值
  businessUrl: http://10.174.13.3:8084/

jedis :
  pool :
    host : 10.45.148.48
    port : 6379
    timeout : 2000
    password : JidaoShowMeTheMonkey
    config :
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis : 100000